---
apiVersion: v1
kind: Pod
metadata:
 name: myapp
spec:
 containers:
   - name: myapp
     image: kumarmitdocker/devops:8

---
apiVersion: v1
kind: Service
metadata:
 name: myapp
spec:
 ports:
 - port: 8084
   targetPort: 8084
selector:
 app: myapp
 tier: myapp
type: LoadBalancer
