---
apiVersion: v1
kind: Pod
metadata:
 name: myapp
spec:
 containers:
   - name: myapp
     image: gcr.io/kubernetes-253920/amancloud1985/apache-ubuntu:v1

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
