apiVersion: v1
kind: Pod
metadata: 
  name: myapp
  labels:
    app: myapp
spec:
  containters:
    - name: myapp
      image: kumarmitdocker/devops:8
      ports:
        - containerPort: 8080
